name: ADFSDump-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday
  workflow_dispatch:
    
jobs:
   
  build:
    
    runs-on: windows-latest
     
    steps:
      - name: Download ADFSDump Main
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://api.github.com/repos/fireeye/ADFSDump/zipball -OutFile "ADFSDump.zip"
              mkdir ADFSDump
              tar -xf ADFSDump.zip -C ADFSDump --strip-components 1
  
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\ADFSDump\ADFSDump.sln
        
      - name: Build Certify
        run: |
              cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\ADFSDump\ADFSDump\ADFSDump.csproj
              
      - uses: actions/upload-artifact@master
        with: 
         name: ADFSDump
         path: ADFSDump\ADFSDump\bin\Debug\ADFSDump.exe 