name: BetterSafetyKatz-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday
  workflow_dispatch:
    
jobs:
   
  build:
    
    runs-on: windows-latest
     
    steps:
      - name: Download BetterSafetyKatz Main
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://api.github.com/repos/Flangvik/BetterSafetyKatz/zipball -OutFile "BetterSafetyKatz.zip"
              mkdir BetterSafetyKatz
              tar -xf BetterSafetyKatz.zip -C BetterSafetyKatz --strip-components 1
  
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\BetterSafetyKatz\BetterSafetyKatz.sln
        
      - name: Build Certify
        run: |
              cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\BetterSafetyKatz\SafetyKatz\BetterSafetyKatz.csproj
              
      - uses: actions/upload-artifact@master
        with: 
         name: BetterSafetyKatz
         path: BetterSafetyKatz\SafetyKatz\bin\Debug\BetterSafetyKatz.exe 