name: Grouper2-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday
  workflow_dispatch:
    
jobs:
   
  build:
    
    runs-on: windows-latest
     
    steps:
      - name: Download Grouper2 Main
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://api.github.com/repos/l0ss/Grouper2/zipball -OutFile "Grouper2.zip"
              mkdir Grouper2
              tar -xf Grouper2.zip -C Grouper2 --strip-components 1
  
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\Grouper2\Grouper2.sln
        
      - name: Build Certify
        run: |
              cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\Grouper2\ConsoleTableExt\ConsoleTableExt.csproj
              
      - uses: actions/upload-artifact@master
        with: 
         name: Grouper2
         path: Grouper2\ConsoleTableExt\bin\Debug\ConsoleTableExt.exe 