name: PurpleSharp-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday
  workflow_dispatch:
    
jobs:
   
  build:
    
    runs-on: windows-latest
     
    steps:
      - name: Download PurpleSharp Main
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://api.github.com/repos/mvelazc0/PurpleSharp/zipball -OutFile "PurpleSharp.zip"
              mkdir PurpleSharp
              tar -xf PurpleSharp.zip -C PurpleSharp --strip-components 1
  
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\PurpleSharp\PurpleSharp.sln
        
      - name: Build Certify
        run: |
              cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\PurpleSharp\PurpleSharp\PurpleSharp.csproj
              
      - uses: actions/upload-artifact@master
        with: 
         name: PurpleSharp
         path: PurpleSharp\PurpleSharp\bin\Debug\PurpleSharp.exe 