name: seatbelt-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday

jobs:
   
  build:
    
    runs-on: windows-latest
    
    steps:
      - name: Build DotNET45
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://github.com/GhostPack/Seatbelt/archive/refs/heads/master.zip -OutFile "Seatbelt.zip"
              tar -xf Seatbelt.zip
              cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\Seatbelt-master\Seatbelt\Seatbelt.csproj
      - uses: actions/upload-artifact@master
        with: 
         name: Seatbelt
         path: Seatbelt-master\Seatbelt\bin\Debug\Seatbelt.exe
