name: Sharp-SMBExec-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday
  workflow_dispatch:
    
jobs:
   
  build:
    
    runs-on: windows-latest
     
    steps:
      - name: Download Sharp-SMBExec Main
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://api.github.com/repos/checkymander/Sharp-SMBExec/zipball -OutFile "Sharp-SMBExec.zip"
              mkdir Sharp-SMBExec
              tar -xf Sharp-SMBExec.zip -C Sharp-SMBExec --strip-components 1
  
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\Sharp-SMBExec\SharpInvoke-SMBExec.sln
        
      - name: Build Certify
        run: |
              cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\Sharp-SMBExec\SharpInvoke-SMBExec\SharpInvoke-SMBExec.csproj
              
      - uses: actions/upload-artifact@master
        with: 
         name: Sharp-SMBExec
         path: Sharp-SMBExec\SharpInvoke-SMBExec\bin\Debug\SharpInvoke-SMBExec.exe 