name: SharpWebServer-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday
  workflow_dispatch:
    
jobs:
   
  build:
    
    runs-on: windows-latest
     
    steps:
      - name: Download SharpWebServer Main
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://api.github.com/repos/mgeeky/SharpWebServer/zipball -OutFile "SharpWebServer.zip"
              mkdir SharpWebServer
              tar -xf SharpWebServer.zip -C SharpWebServer --strip-components 1
  
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\SharpWebServer\SharpWebServer.sln
        
      - name: Build Certify
        run: |
              cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpWebServer\SharpWebServer\SharpWebServer.csproj
              
      - uses: actions/upload-artifact@master
        with: 
         name: SharpWebServer
         path: SharpWebServer\SharpWebServer\bin\Debug\SharpWebServer.exe 