name: SharpHound3-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday
  workflow_dispatch:
    
jobs:
   
  build:
    
    runs-on: windows-latest
     
    steps:
      - name: Download SharpHound3 Main
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://api.github.com/repos/BloodHoundAD/SharpHound3/zipball -OutFile "SharpHound3.zip"
              mkdir SharpHound3
              tar -xf SharpHound3.zip -C SharpHound3 --strip-components 1
  
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\SharpHound3\SharpHound3.sln
        
      - name: Build Certify
        run: |
              cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpHound3\SharpHound3\SharpHound3.csproj
              
      - uses: actions/upload-artifact@master
        with: 
         name: SharpHound3
         path: SharpHound3\SharpHound3\bin\Debug\SharpHound3.exe 