name: SharpSphere-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday
  workflow_dispatch:
    
jobs:
   
  build:
    
    runs-on: windows-latest
     
    steps:
      - name: Download SharpSphere Main
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://api.github.com/repos/JamesCooteUK/SharpSphere/zipball -OutFile "SharpSphere.zip"
              mkdir SharpSphere
              tar -xf SharpSphere.zip -C SharpSphere --strip-components 1
  
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\SharpSphere\SharpSphere.sln
        
      - name: Build Certify
        run: |
              cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpSphere\SharpSphere\SharpSphere.csproj
              
      - uses: actions/upload-artifact@master
        with: 
         name: SharpSphere
         path: SharpSphere\SharpSphere\bin\Debug\SharpSphere.exe 