name: Shhmon-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday
  workflow_dispatch:
    
jobs:
   
  build:
    
    runs-on: windows-latest
     
    steps:
      - name: Download Shhmon Main
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://api.github.com/repos/matterpreter/Shhmon/zipball -OutFile "Shhmon.zip"
              mkdir Shhmon
              tar -xf Shhmon.zip -C Shhmon --strip-components 1
  
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\Shhmon\Shhmon.sln
        
      - name: Build Certify
        run: |
              cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\Shhmon\Shhmon\Shhmon.csproj
              
      - uses: actions/upload-artifact@master
        with: 
         name: Shhmon
         path: Shhmon\Shhmon\bin\Debug\Shhmon.exe 