name: SweetPotato-build

on:
  schedule:
    - cron: '0 11 * * *' # runs at 11:00 UTC everyday
  workflow_dispatch:
    
jobs:
   
  build:
    
    runs-on: windows-latest
     
    steps:
      - name: Download SweetPotato Main
        run: | 
              cd $Env:GITHUB_WORKSPACE
              powershell Invoke-WebRequest -URI https://api.github.com/repos/CCob/SweetPotato/zipball -OutFile "SweetPotato.zip"
              mkdir SweetPotato
              tar -xf SweetPotato.zip -C SweetPotato --strip-components 1
  
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\SweetPotato\SweetPotato.sln
        
      - name: Build Certify
        run: |
              cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
              .\MSBuild.exe $Env:GITHUB_WORKSPACE\SweetPotato\SweetPotato.csproj
              
      - uses: actions/upload-artifact@master
        with: 
         name: SweetPotato
         path: SweetPotato\bin\Debug\SweetPotato.exe 